routes/web.php
<?php

Route::get('/',function(){ return redirect()->route('login'); });

Route::group(['namespace' => 'Auth'], function(){
    
    Route::get('login', ['as' => 'login', 'uses' => 'LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'LoginController@logout']);
});

Route::group(['middleware' => 'auth'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'SystemSet\Language\LanguageController@setLocale', 'as' => 'language.set-locale']);

    Route::get('/dashboard',['uses' => 'Dashboard\DashboardController@index','as' => 'dashboard']);

    Route::group(['namespace' => 'User'],function(){
        Route::group(['middleware' => ['permission:user-take-cash']], function () {
            Route::resource('/users/account/takecash', 'AccountTakeCashController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:user-recharge']], function () {
            Route::resource('/users/account/recharge', 'AccountRechargeController',['as' => 'users.account']);
        });
        Route::group(['middleware' => ['permission:view-user-account-log']], function () {
            Route::resource('/users/account/logs', 'AccountLogController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account']], function () {
            Route::resource('/users/accounts', 'AccountController',['as' => 'users']);
        });
        Route::group(['middleware' => ['permission:view-user-account|view-user-account-log|user-recharge|user-take-cash']], function () {
            Route::resource('/users/sale-network', 'SaleNetworkController',['as' => 'users']);
            Route::resource('/users/direct-user', 'DirectUserController',['as' => 'users']);
        });
    });

    Route::group(['namespace' => 'Order'],function(){
        Route::group(['middleware' => ['permission:export-order-list']], function () {
            Route::get('/orders/temp/download',['uses' => 'OrderTempController@downloadExcel', 'as' => 'orders.temp.download']);
        });
        Route::group(['middleware' => ['permission:export-history-report']], function () {
            Route::get('/orders/report/download',['uses' => 'OrderController@downloadExcel', 'as' => 'orders.report.download']);
        });

        Route::group(['middleware' => ['permission:view-order-list']], function () {
            Route::get('/orders/temp/{ticket}/get-order-detail',['uses' => 'OrderTempController@ajaxGetOrderDetail', 'as' => 'orders.temp.get-order-detail']);
            Route::resource('/orders/temp', 'OrderTempController',['as' => 'orders']);
        });

        Route::group(['middleware' => ['permission:view-history-report']], function () {
            Route::get('/orders/report/{ticket}/get-order-detail',['uses' => 'OrderController@ajaxGetOrderDetail', 'as' => 'orders.report.get-order-detail']);
            Route::get('/orders/report/selection-form',['uses' => 'OrderController@showSelectionForm','as' => 'orders.report.selection-form']);
            Route::resource('/orders/report', 'OrderController',['as' => 'orders']);
        });
    });

    Route::group(['namespace' => 'Finance'],function(){
        Route::group(['middleware' => ['permission:download-transaction-log']], function () {
            Route::get('/finance/accounts/logs/download', ['uses' => 'AccountLogController@download','as' => 'accounts.logs.download']);
        });
        Route::group(['middleware' => ['permission:view-transaction-log']], function () {
            Route::resource('/finance/accounts/logs', 'AccountLogController',['as' => 'accounts']);    
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/transfer', 'AccountTransferController',['as' => 'accounts']);
        });
        Route::group(['middleware' => ['permission:platform-account-access-transfer']], function () {
            Route::resource('/finance/accounts/deposit', 'AccountDepositController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:add-class-manager']], function () {
            Route::resource('/finance/accounts/categories', 'AccountCategoryController',['as' => 'accounts']);
        });   
        Route::group(['middleware' => ['permission:view-platform-account|add-new-account']], function () {
            Route::resource('/finance/accounts', 'AccountController'); 
        });
    });

    Route::group(['namespace' => 'Cycle'],function(){
        Route::group(['middleware' => ['permission:view-lottery-log']], function () {
            Route::resource('/cycles/logs', 'CycleLogController',['as' => 'cycles']);
        });
        Route::group(['middleware' => ['permission:lottery-setting']], function () {
            Route::resource('/cycles/set', 'CycleSetController',['as' => 'cycles']);
        });
        Route::group(['middleware' => ['permission:lottery-operation']], function () {
            Route::get('cycles/result/set',['uses' => 'ResultSettleController@setResultForm','as' => 'cycles.result.set']);
            Route::post('cycles/result/set',['uses'  => 'ResultSettleController@setResult','as' => 'cycles.result.set']);
        });
        Route::group(['middleware' => ['permission:billing-operation']], function () {
            Route::get('cycles/result/settle',['uses' => 'ResultSettleController@settleResultLoading','as' => 'cycles.result.settle']);
            Route::post('cycles/result/settle',['uses' => 'ResultSettleController@settleResult','as' => 'cycles.result.settle']);
            Route::post('ajax/cycle/result/settle',['uses' => 'ResultSettleController@ajaxSettleResult','as' => 'ajax.cycles.result.settle']);
        });
    });

    Route::group(['namespace' => 'Profit'],function(){
        Route::group(['middleware' => ['permission:lucky-draw']], function () {
            Route::resource('/profit/lucky-draw', 'LuckyDrawController',['as' => 'profit']);
        });
    });

    Route::group(['namespace' => 'Manager'],function(){
        Route::group(['middleware' => ['permission:add-new-role|view-role|role-modification']], function () {
            Route::resource('/managers/roles', 'ManagerRoleController',['as' => 'managers']);
        });
        Route::group(['middleware' => ['permission:view-manager-log']], function () {
            Route::resource('/managers/logs', 'ManagerLogController',['as' => 'managers']);
        });

        Route::resource('/managers/password','ManagerEditPasswordController',['as' => 'managers']);
        Route::group(['middleware' => ['permission:add-new-manager-account|view-manager-account|manager-account-modification']], function () {
            Route::resource('/managers', 'ManagerController');
        });
    });

    Route::group(['namespace' => 'Game'],function(){
        Route::group(['middleware' => ['permission:view-game-type-setting|game-type-modification']], function () {
            Route::resource('/games/types', 'GameTypeController',['as' => 'games']);
        });
        Route::group(['middleware' => ['permission:view-game-rebate-setting|game-rebate-modification']], function () {
            Route::resource('/games/rebates', 'GameRebateController',['as' => 'games']);
        });
        Route::group(['middleware' => ['permission:view-game-promotion|game-promotion-modification']], function () {
            Route::resource('/games/promotion', 'GamePromotionController',['as' => 'games']);
        });
    });    
    
    Route::group(['namespace' => 'SystemSet','as' => 'system-set.'],function(){
        Route::group(['middleware' => ['permission:view-exchange-rate-set|exchange-rate-modification']], function () {
            Route::resource('/system-set/exchange-rate', 'ExchangeRate\ExchangeRateController');
        });
        Route::group(['middleware' => ['permission:view-language-set|language-set-modification']], function () {
            Route::resource('/system-set/languages/admin', 'Language\LanguageAdminController',['as' => 'languages']);
            Route::resource('/system-set/languages/api', 'Language\LanguageApiController',['as' => 'languages']);
        });
        Route::group(['middleware' => ['permission:view-location-set|location-set-modification']], function () {
            Route::resource('/system-set/locations/provinces', 'Location\ProvinceController',['as' => 'locations']);
            Route::resource('/system-set/locations/districts', 'Location\DistrictController',['as' => 'locations']);
            Route::resource('/system-set/locations/communes', 'Location\CommuneController',['as' => 'locations']);
        });
    });

    Route::group(['namespace' => 'Analysis'],function(){
        Route::group(['middleware' => ['permission:analysis-operation']], function () {
            Route::resource('/analysis', 'ResultAnalysisController');
        });
    });

    // Ajax Routes
    Route::get('get-district-by-province',['uses' => 'SystemSet\Location\DistrictController@getDistrictsByProvinceId', 'as' => 'locations.get-districts-by-province']);
    Route::get('get-system-account-log-info/{id}',['uses' => 'Finance\AccountLogController@ajaxGetLogInformation', 'as' => 'system.account.getLogInfo']);
    Route::get('get-user-account-log-info/{id}',['uses' => 'User\AccountLogController@ajaxGetLogInformation', 'as' => 'user.account.getLogInfo']);
    
    
}); 

app/Http/Controllers/SystemSet/Location/CommuneController.php
<?php

namespace App\Http\Controllers\SystemSet\Location;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Commune;
use App\Model\District;
use App\Model\Province;
use DB;

class CommuneController extends Controller
{
    public function index()
    {   
        $communes = Commune::with('district','district.province')
                            ->when(request()->district_id && request()->district_id != 0,function($q){
                                return $q->whereDistrictId(request()->district_id);
                            })
                            ->orderBy('district_id','ASC')
                            ->orderBy('name','ASC')->paginate(40);
        $districts = ['0' => 'All'] + District::orderBy('name','ASC')->pluck('name','id')->toArray();
        return view('system-set.location.commune.index',compact('communes','districts'));
    }

    public function create()
    {
        $provinces = ['0' => 'Choose'] + Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        $districts = request()->province_id ? ['0' => 'Choose'] + District::orderBy('name','ASC')->pluck('name','id')->toArray() : ['0' => 'Choose'];
        return view('system-set.location.commune.add-update',compact('provinces','districts'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:communes,name'
        ]);
        $this->saveToDB($request->all());
        return redirect()->route('system-set.locations.communes.index')->withSuccess('You have just added a commune successfully!');    
    }

    public function edit($id)
    {
        $commune = Commune::with('district','district.province')->whereId($id)->first();
        $provinces = ['0' => 'Choose'] + Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        $districts = $commune->district && $commune->district->province 
                        ? District::orderBy('name','ASC')
                                ->whereProvinceId($commune->district->province->id)
                                ->pluck('name','id')->toArray()
                        : ['0' => 'Choose'];
        return view('system-set.location.commune.add-update',compact('commune','provinces','districts'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|unique:communes,name,'.$id
        ]);
        $this->saveToDB($request->all(),$id);
        return redirect()->route('system-set.locations.communes.index')->withSuccess('You have just updated a commune successfully!');  
    }

    public function destroy($id)
    {
        $result = false;
        $item = Commune::findOrFail($id);
        if($item){
            DB::beginTransaction();
            try{
                if($item->delete()){
                    $result = true;
                }
                DB::commit();
            }catch(Exception $exception){
                DB::rollback();
                $result = false;
            }
        }
        return response()->json(['success' => $result]);
    }

    public function saveToDB($data, $id=null){
        $commune = isset($id) ? Commune::find($id) : new commune;
        DB::beginTransaction();
        try{
            if(!$commune) return redirect()->back()->withError('There is no record found!');
            $commune->fill($data);
            $commune->save();
            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $commune;
    }
}

app/Http/Controllers/SystemSet/Location/DistrictController.php
<?php

namespace App\Http\Controllers\SystemSet\Location;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\District;
use App\Model\Province;
use DB;

class DistrictController extends Controller
{
    public function index()
    {
        $districts = District::with('province')
                                ->when(request()->province_id && request()->province_id != 0,function($q){
                                    return $q->whereProvinceId(request()->province_id);
                                })
                                ->orderBy('province_id','ASC')
                                ->orderBy('name','ASC')->paginate(40);
        $provinces = ['0' => 'All'] + Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        return view('system-set.location.district.index',compact('districts','provinces'));
    }

    public function create()
    {
        $provinces = Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        return view('system-set.location.district.add-update',compact('provinces'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:districts,name'
        ]);
        $this->saveToDB($request->all());
        return redirect()->route('system-set.locations.districts.index')->withSuccess('You have just added a district successfully!');    
    }

    public function edit($id)
    {
        $district = District::findOrFail($id);
        $provinces = Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        return view('system-set.location.district.add-update',compact('district','provinces'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|unique:districts,name,'.$id
        ]);
        $this->saveToDB($request->all(),$id);
        return redirect()->route('system-set.locations.districts.index')->withSuccess('You have just updated a district successfully!');  
    }

    public function destroy($id)
    {
        $result = false;
        $item = District::findOrFail($id);
        if($item){
            DB::beginTransaction();
            try{
                if($item->delete()){
                    $result = true;
                }
                DB::commit();
            }catch(Exception $exception){
                DB::rollback();
                $result = false;
            }
        }
        return response()->json(['success' => $result]);
    }

    public function getDistrictsByProvinceId(){
        $districts = District::whereProvinceId(request()->id)->pluck('name','id')->toArray();
        return response()->json(['success' => true, 'data' => $districts]);
    }

    public function saveToDB($data, $id=null){
        $district = isset($id) ? District::find($id) : new District;
        DB::beginTransaction();
        try{
            if(!$district) return redirect()->back()->withError('There is no record found!');
            $district->fill($data);
            $district->save();
            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $district;
    }
}

resources/views/system-set/location/commune/add-update.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Commune</span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route('system-set.locations.communes.index') }}" class="btn btn-sm btn-primary">
                    <i class="icon-square-left mr-1"></i> Back
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <a href="{{route('system-set.locations.provinces.index')}}"  class="breadcrumb-item">{{ $settings['language']['LANG_MENU_SYSTEM_SET'] }}</span>
                <a href="{{route('system-set.locations.communes.index')}}"  class="breadcrumb-item">Location Set</a>
                <a href="{{route('system-set.locations.communes.index')}}"  class="breadcrumb-item">Commune</a>
                <span class="breadcrumb-item active">{{ isset($commune) ? 'Edit' : 'Add'}}</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    <div class="card">
        @if(isset($commune))
        {{ Form::model($commune,['route' => ['system-set.locations.communes.update',$commune->id], 'method' => 'PUT']) }}
        @else
        {{ Form::open(['route' => 'system-set.locations.communes.store', 'method' => 'POST']) }}
        @endif
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group select2">
                        <label>Province</label>
                        {{Form::select("province_id",$provinces, isset($commune) && $commune->district && $commune->district->province ? $commune->district->province->id : null,
                                        ["class" => "form-control",'id' => 'province', 'data-route' => route('locations.get-districts-by-province')])}}
                    </div>
                    <div class="form-group select2">
                        <label>District</label>
                        {{Form::select("district_id",$districts, isset($commune) && $commune->district ? $commune->district->id : null,
                            ["class" => "form-control", 'id' => 'district'])}}
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible {{ $errors->has('name')?'text-danger':'' }}">Commune Name</label>
                        <div class="position-relative">
                            {{Form::text("name",null,
                                ["class" => "form-control ".($errors->has('name')?'border-danger':''),"placeholder" => "Enter commune name"])
                            }}
                            @if($errors->has('name'))
                                <div class="form-control-feedback text-danger">
                                    <i class="icon-spam"></i>
                                </div>
                            @endif
                        </div>
                        @if($errors->has('name'))
                            <span class="form-text text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group form-group-float form-group-feedback form-group-feedback-right">
                        <label class="form-group-float-label font-weight-semibold is-visible">Commune Code</label>
                        <div class="position-relative">
                            {{Form::text("code",null,
                                ["class" => "form-control ","placeholder" => "Enter commune code"])
                            }}
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon-folder mr-1"></i> {{$settings['language']['LANG_LABEL_POST']}}
            </button>
        </div>
        {{ Form::close() }}
    </div>
</div>
@endsection

@section('custom-js')
<script>
    $(document).ready(function(){
        if($('#province').length > 0){
            $('#province').change(function(){
                $.ajax({
                    type:'GET',  
                    url:$(this).data('route') + '?id=' + $(this).val(),
                    dataType: "JSON",
                    data: {},
                    success:function(response){
                        if(response.success){
                            $('#district').html('');
                            let body = '<option value=0>Choose</option>';
                            jQuery.map( response.data, function( n, i ) {
                                body += '<option value='+i+'>'+n+'</option>'  
                            });
                            $('#district').html(body);
                        }else{
                            swalOnResult('Error While Deleting!','error');
                        }
                    },
                    error:function(){
                        swalOnResult('Error While Deleting!','error');
                    }
                });
            });
        }
    })
</script>
@endsection

resources/views/system-set/location/commune/index.blade.php
@extends('layouts.master')

@section('content')
<!-- Page header -->
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex py-2">
            <h4><span class="font-weight-semibold">Location Set</span></h4>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Dashboard</a>
                <span class="breadcrumb-item active">{{ $settings['language']['LANG_MENU_SYSTEM_SET'] }}</span>
                <span class="breadcrumb-item active">Location Set</span>
                <span class="breadcrumb-item active">Commune</span>
            </div>
        </div>
    </div>
</div>
<!-- /page header -->

<div class="content">
    @include('includes.error-msg')
    @include('includes.success-msg')
    <div class="card">
        <div class="card-header">
            {{ Form::open(['route' => 'system-set.locations.communes.index', 'method' => 'GET', 'class' => 'form-inline d-block d-sm-flex']) }}
                <div class="form-group mb-2 mr-sm-2">
                    <div class="btn-group btn-group-sm w-100">
                        <a href="{{route('system-set.locations.provinces.index')}}" class="btn {{ Route::currentRouteName() == 'system-set.locations.provinces.index' ? 'btn-primary': 'btn-secondary' }}">Province</a>
                        <a href="{{route('system-set.locations.districts.index')}}" class="btn {{ Route::currentRouteName() == 'system-set.locations.districts.index' ? 'btn-primary': 'btn-secondary' }}">District</a>
                        <a href="{{route('system-set.locations.communes.index')}}" class="btn {{ Route::currentRouteName() == 'system-set.locations.communes.index' ? 'btn-primary': 'btn-secondary' }}">Commune</a>
                    </div>
                </div>
                <div class="form-group mb-2 mr-sm-2">
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <div class="input-group-text">District</div>
                        </div>
                        {{Form::select("district_id",$districts, isset($_GET['district_id']) ? $_GET['district_id'] : null,
                            ["class" => "form-control input-sm", 'id' => 'district'])}}
                    </div>
                </div>
                <div class="form-group mb-2 mr-sm-2 ml-auto">
                    <div class="input-group input-group-sm">
                        <a href="{{ route('system-set.locations.communes.create') }}" class="btn btn-sm btn-primary w-100">
                            <i class="icon-plus3"></i> Add
                        </a>
                    </div>
                </div>
            {{ Form::close() }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr class="bg-slate-800">
                                    <th>Province Name</th>
                                    <th>District Name</th>
                                    <th>Commune Name</th>
                                    <th>Code</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($communes) && $communes->count() > 0)
                                    @foreach($communes as $row)
                                        <tr>
                                            <td>{{ $row->district && $row->district->province ? $row->district->province->name : '' }}</td>
                                            <td>{{ $row->district ? $row->district->name : '' }}</td>
                                            <td>{{ $row->name }}</td>
                                            <td>{{ $row->code }}</td>
                                            <td class="group-btn-action">
                                                @canany(['location-set-modification'])
                                                <div class="btn-group">
                                                    <a href="{{ route('system-set.locations.communes.edit',$row->id) }}" class="btn btn-sm btn-outline bg-primary border-primary text-primary-800 btn-icon border-2"><i class="icon-pencil7"></i> Edit</a>
                                                    <button type="button" class="btn btn-sm btn-outline bg-danger border-danger text-danger-800 btn-icon border-2 delete" data-route="{{route('system-set.locations.communes.destroy',$row->id)}}"><i class="icon-trash"></i> Delete</a>
                                                </div>
                                                @endcanany    
                                            </td>
                                        </tr>
                                    @endforeach
                                @else 
                                    <tr><td colspan="5">No Data</td></tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        @if(isset($communes) && $communes->count() >0)
        <div class="card-footer">
            @if($communes->hasMorePages())
            <div class="mb-2">
                {!! $communes->appends(Input::except('page'))->render() !!}
            </div>
            @endif
            <div>
                Showing {{ $communes->firstItem() }} to {{ $communes->lastItem() }}
                of  {{$communes->total()}} entries
            </div>
        </div>
        @endif
    </div>
</div>
@endsection

@section('custom-js')
<script>
    $(document).ready(function(){
        if($('#district').length > 0){
            $('#district').change(function(){
                $('#district').parents('form').submit();
            });
        }
    })
</script>
@endsection